export const users = [
  {
    id: 1,
    name: "Leslie Alexander",
    email: "leslie.alexander@example.com",
    time: "10:00 PM",
    image: "/images/a1.png",
  },
  {
    id: 2,
    name: "Michael Foster",
    email: "michael.foster@example.com",
    time: "09:45 PM",
    image: "/images/a2.png",
  },
  {
    id: 3,
    name: "Courtney Henry",
    email: "courtney.henry@example.com",
    time: "08:30 PM",
    image: "/images/a3.png",
  },
  {
    id: 4,
    name: "Eleanor Pena",
    email: "eleanor.pena@example.com",
    time: "07:10 PM",
    image: "/images/a4.png",
  },
  {
    id: 5,
    name: "Devon Lane",
    email: "devon.lane@example.com",
    time: "06:50 PM",
    image: "/images/a5.png",
  },
  {
    id: 6,
    name: "Leslie Alexander",
    email: "leslie.alexander@example.com",
    time: "10:00 PM",
    image: "/images/a1.png",
  },
  {
    id: 7,
    name: "Michael Foster",
    email: "michael.foster@example.com",
    time: "09:45 PM",
    image: "/images/a2.png",
  },
  {
    id: 8,
    name: "Courtney Henry",
    email: "courtney.henry@example.com",
    time: "08:30 PM",
    image: "/images/a3.png",
  },
  {
    id: 9,
    name: "Eleanor Pena",
    email: "eleanor.pena@example.com",
    time: "07:10 PM",
    image: "/images/a4.png",
  },
  {
    id: 10,
    name: "Devon Lane",
    email: "devon.lane@example.com",
    time: "06:50 PM",
    image: "/images/a5.png",
  },
];
